export const genresList = [
    {genre: 'Бизнес-книги', amount: 12 },
    {genre: 'Детективы', amount: 8 },
    {genre: 'Детские книги', amount: 2 },
    {genre: 'Зарубежная литература', amount: 5 },
    {genre: 'История', amount: 3 },
    {genre: 'Классическая литература', amount: 6 },
    {genre: 'Книги по психологии', amount: 12 },
    {genre: 'Компьютерная литература', amount: 5 },
    {genre: 'Культура и искусство', amount: 12 },
    {genre: 'Наука и образование', amount: 14 },
    {genre: 'Публицистическая литература', amount: 2 },
    {genre: 'Справочники', amount: 1 },
    {genre: 'Фантастика', amount: 10 },
    {genre: 'Юмористическая литература', amount: 6 },
]

// ,
//   "foreignLiterature": [],
//   "historyLiterature": [],
//   "classicLiterature": [],
//   "psychologyLiterature": [],
//   "computerLiterature": [],
//   "cultureLiterature": [],
//   "scienceLiterature": [],
//   "journalisticLiterature": [],
//   "directoryLiterature": [],
//   "fantasticLiterature": [],
//   "humorousLiterature": []